### ISSUE TITLE
xmlPath incorrectly handles namespaces with item selector (item[0])

### ISSUE THREAD

**Issue by rzeh4n** [jayway/rest-assured#647]
I have 3 versions of xml file, two of them declare namespaces.
/test/ns_none:
```
<?xml version="1.0" encoding="UTF-8"?>
<response note="something">
    <container cont_id="some_id">
        <item id="i_1">
            <name>first</name>
        </item>
        <item id="i_2">
            <name>second</name>
        </item>
        <item id="i_3">
            <name>third</name>
        </item>
    </container>
</response>
```
/test/ns_default:
```
<?xml version="1.0" encoding="UTF-8"?>
<response xmlns="http://something.com/test" note="something">
    <container cont_id="some_id">
        <item id="i_1">
            <name>first</name>
        </item>
        <item id="i_2">
            <name>second</name>
        </item>
        <item id="i_3">
            <name>third</name>
        </item>
    </container>
</response>
```
/test/ns_prefixed:
```
<?xml version="1.0" encoding="UTF-8"?>
<x:response xmlns:x="http://something.com/test" note="something">
    <x:container cont_id="some_id">
        <x:item id="i_1">
            <x:name>first</x:name>
        </x:item>
        <x:item id="i_2">
            <x:name>second</x:name>
        </x:item>
        <x:item id="i_3">
            <x:name>third</x:name>
        </x:item>
    </x:container>
</x:response>
```
Here is my code:
```
@Test
    public void somethingTest() {
        RestAssuredConfig config = newConfig().xmlConfig(xmlConfig().with().namespaceAware(true).declareNamespace("x", "http://something.com/test"));
        XmlPathConfig xmlPathConfig = xmlPathConfig().declaredNamespace("x", "http://something.com/test");

        System.out.println("NO NAMESPACE");
        String xml = with().config(config).when().get("/test/ns_none").andReturn().asString();
        XmlPath xmlPath = XmlPath.from(xml).using(xmlPathConfig);
        System.out.println("items: " + xmlPath.get("response.container.item"));
        System.out.println("item 1: " + xmlPath.get("response.container.item[0]"));
        System.out.println("item 1 name: " + xmlPath.get("response.container.item[0].name"));
        System.out.println("item 1 id: " + xmlPath.get("response.container.item[0].@id"));
        System.out.println();

        System.out.println("DEFAULT NAMESPACE");
        xml = with().config(config).when().get("/test/ns_default").andReturn().asString();
        xmlPath = XmlPath.from(xml).using(xmlPathConfig);
        System.out.println("items: " + xmlPath.get("x:response.x:container.x:item"));
        // System.out.println("item 1: " + xmlPath.get("x:response.x:container.item[0]")); //invalid path
        System.out.println("item 1: " + xmlPath.get("x:response.x:container.item[0]"));
        System.out.println("item 1 name: " + xmlPath.get("x:response.x:container.item[0].x:name"));
        System.out.println("item 1 id: " + xmlPath.get("x:response.x:container.item[0].@id"));
        System.out.println();

        System.out.println("PREFIXED NAMESPACE");
        xml = with().config(config).when().get("/test/ns_prefixed").andReturn().asString();
        xmlPath = XmlPath.from(xml).using(xmlPathConfig);
        System.out.println("items: " + xmlPath.get("x:response.x:container.x:item"));
        // System.out.println("item 1: " + xmlPath.get("x:response.x:container.x:item[0]")); //invalid path
        System.out.println("item 1: " + xmlPath.get("x:response.x:container.item[0]"));
        System.out.println("item 1 name: " + xmlPath.get("x:response.x:container.item[0].x:name"));
        System.out.println("item 1 id: " + xmlPath.get("x:response.x:container.item[0].@id"));
        System.out.println();
    }
```
And printout:
```
NO NAMESPACE
items: firstsecondthird
item 1: first
item 1 name: first
item 1 id: i_1

DEFAULT NAMESPACE
items: firstsecondthird
item 1: first
item 1 name: first
item 1 id: i_1

PREFIXED NAMESPACE
items: firstsecondthird
item 1: first
item 1 name: first
item 1 id: i_1
```

My problem is here for both versions with namespace:
```
System.out.println("items: " + xmlPath.get("x:response.x:container.x:item"));
// System.out.println("item 1: " + xmlPath.get("x:response.x:container.item[0]")); //invalid path
```
There mustn't by any prefix before item even though item is in the declared namespaces. But only when I select item with []. When i add prefix (uncomment line), i get following error:
```
FAILED: somethingTest
java.lang.IllegalArgumentException: Invalid path:
expecting EOF, found ':' @ line 1, column 41.
   dXmlRoot'x:response'.'x:container'.x:item[0]
                                       ^

1 error

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
	at com.jayway.restassured.assertion.XMLAssertion.getResult(XMLAssertion.groovy:99)
	at com.jayway.restassured.path.xml.XmlPath.getFromPath(XmlPath.java:433)
	at com.jayway.restassured.path.xml.XmlPath.get(XmlPath.java:321)
	at cz.nkp.urnnbn.api.v3.RegistrarsTest.somethingTest(RegistrarsTest.java:145)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
```
I don't see any reason why in this particular case the element should not be prefixed.

**Comment by johanhaleby** [comment]
Does it work if you also escape x:item? I.e.

```java
'x:response'.'x:container'.'x:item'[0]
```

**Comment by rzeh4n** [comment]
Yes, that does help and test now passes. But i noticed, that namespace handling is overall strange. I extended the ns_prefixed.xml and included one item element without prefix (i.e. in empty/global namespace):
```
<?xml version="1.0" encoding="UTF-8"?>
<x:response xmlns:x="http://something.com/test" note="something">
    <x:container cont_id="some_id">
        <x:item id="i_1">
            <x:name>first</x:name>
        </x:item>
        <x:item id="i_2">
            <x:name>second</x:name>
        </x:item>
        <x:item id="i_3">
            <x:name>third</x:name>
        </x:item>
        <item id="i_4">
            <name>fourth</name>
        </item>
    </x:container>
</x:response>
```
And changed rows in test method:
```
// System.out.println("item 1 (prefixed): " + xmlPath.get("x:response.x:container.x:item[0]")); // should be ok, but invalid path error
System.out.println("item 1 (not prefixed): " + xmlPath.get("response.container.item[0]"));// should be empty
System.out.println("item 1 (prefixed, elements in ''): " + xmlPath.get("'x:response'.'x:container'.'x:item'[0]"));// ok

// System.out.println("item 4 (prefixed): " + xmlPath.get("x:response.x:container.x:item[3]")); // should be empty, but invalid path error
System.out.println("item 4 (not prefixed): " + xmlPath.get("x:response.x:container.item[3]"));// ok
System.out.println("item 4 (prefixed, elements in ''): " + xmlPath.get("'x:response'.'x:container'.'x:item'[3]"));// should be empty, but invalid path error
```
The result was:
```
item 1 (not prefixed): first
item 1 (prefixed, elements in ''): first
item 4 (not prefixed): fourth
item 4 (prefixed, elements in ''): 
```
So what I think is incorrect:
**x:response.x:container.x:item[0]** - should return first node, instead produces invalid path error
**response.container.item[0]** - returns first item's content, but should be empty. There are no elements response, container or item in global namespace.
**x:response.x:container.x:item[3]** - shuld return null (there are only 3 x:item elements), but results in path error. 
**'x:response'.'x:container'.'x:item'[3]** - should be null, but returns element item[0], not x:item[3] which doesn't exist.

**Comment by johanhaleby** [comment]
There are a couple of things here that should be addressed. First of all what version of REST Assured are you using? Secondly here's my test case (which works):

```java
@Test public void
xml_path_supports_declared_namespaces() {
    // Given
    String xml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
            "<x:response xmlns:x=\"http://something.com/test\" note=\"something\">\n" +
            "    <x:container cont_id=\"some_id\">\n" +
            "        <x:item id=\"i_1\">\n" +
            "            <x:name>first</x:name>\n" +
            "        </x:item>\n" +
            "        <x:item id=\"i_2\">\n" +
            "            <x:name>second</x:name>\n" +
            "        </x:item>\n" +
            "        <x:item id=\"i_3\">\n" +
            "            <x:name>third</x:name>\n" +
            "        </x:item>\n" +
            "        <item id=\"i_4\">\n" +
            "            <name>fourth</name>\n" +
            "        </item>\n" +
            "    </x:container>\n" +
            "</x:response>";

    // When
    XmlPath xmlPath = new XmlPath(xml).using(xmlPathConfig().declaredNamespace("x", "http://something.com/test"));

    // Then
    assertThat(xmlPath.getString("x:response.'x:container'.'x:item'[0].x:name"), equalTo("first"));
    assertThat(xmlPath.getString("response.container.':item'[0].name"), equalTo("fourth"));
    assertThat(xmlPath.getString("x:response.'x:container'.'x:item'[3].x:name"), isEmptyOrNullString());
    assertThat(xmlPath.getString("'x:response'.'x:container'.'x:item'[3].x:name"), isEmptyOrNullString());
}
```

I believe that is correct if we ignore the need for escaping. _That_ is something that should be addressed. I don't really know why we need to escape 'x:container' though but the others makes sense to me (but you shouldn't need to). Here's another set of tests to show you how it works:

```java
@Test public void
xml_path_supports_namespaces_when_declared_correctly() {
    // Given
    String xml = "<foo xmlns:ns=\"http://localhost/\">\n" +
            "      <bar>sudo </bar>\n" +
            "      <ns:bar>make me a sandwich!</ns:bar>\n" +
            "    </foo>";

    // When
    XmlPath xmlPath = new XmlPath(xml).using(xmlPathConfig().declaredNamespace("ns", "http://localhost/"));

    // Then
    assertThat(xmlPath.getString("foo.bar.text()"), equalTo("sudo make me a sandwich!"));
    assertThat(xmlPath.getString(":foo.:bar.text()"), equalTo("sudo "));
    assertThat(xmlPath.getString(":foo.ns:bar.text()"), equalTo("make me a sandwich!"));
}

@Test public void
xml_path_doesnt_support_namespaces_when_not_declared() {
    // Given
    String xml = "<foo xmlns:ns=\"http://localhost/\">\n" +
            "      <bar>sudo </bar>\n" +
            "      <ns:bar>make me a sandwich!</ns:bar>\n" +
            "    </foo>";

    // When
    XmlPath xmlPath = new XmlPath(xml);

    // Then
    assertThat(xmlPath.getString("foo.bar.text()"), equalTo("sudo make me a sandwich!"));
    assertThat(xmlPath.getString(":foo.:bar.text()"), equalTo("sudo "));
    assertThat(xmlPath.getString(":foo.ns:bar.text()"), equalTo(""));
}
```

Does it make sense? REST Assured follows the semantics of `XmlSlurper` in Groovy.

**Comment by johanhaleby** [comment]
I've now deployed a new snapshot that should address the need for manually escaping. Please try version `2.8.1-SNAPSHOT` after having added the following Maven repository:

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```

My test now looks like this:

```java
@Test public void
xml_path_supports_declared_namespaces_without_manual_escaping() {
    // Given
    String xml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
            "<x:response xmlns:x=\"http://something.com/test\" note=\"something\">\n" +
            "    <x:container cont_id=\"some_id\">\n" +
            "        <x:item id=\"i_1\">\n" +
            "            <x:name>first</x:name>\n" +
            "        </x:item>\n" +
            "        <x:item id=\"i_2\">\n" +
            "            <x:name>second</x:name>\n" +
            "        </x:item>\n" +
            "        <x:item id=\"i_3\">\n" +
            "            <x:name>third</x:name>\n" +
            "        </x:item>\n" +
            "        <item id=\"i_4\">\n" +
            "            <name>fourth</name>\n" +
            "        </item>\n" +
            "    </x:container>\n" +
            "</x:response>";

    // When
    XmlPath xmlPath = new XmlPath(xml).using(xmlPathConfig().declaredNamespace("x", "http://something.com/test"));

    // Then
    assertThat(xmlPath.getString("x:response.x:container.x:item[0].x:name"), equalTo("first"));
    assertThat(xmlPath.getString("response.container.:item[0].name"), equalTo("fourth"));
    assertThat(xmlPath.getString("x:response.x:container.x:item[3].x:name"), isEmptyOrNullString());
    assertThat(xmlPath.getString("'x:response'.x:container.x:item[3].x:name"), isEmptyOrNullString());
}
```

I'll close this issue now. Please tell me if you don't agree.

**Comment by rzeh4n** [comment]
Thanks, I think that the 2.8.1-SNAPSHOT version does fix the "need to escape x:item[0]" problem. I still have some ideas about namespace handling though, but I'll address that in separate issue.
